import {
  BOOLEAN_FALSE,
  BOOLEAN_TRUE,
  CHAT_STICK_THRESHOLD_PX,
  FOUR_HUNDRED,
  LABEL_NEW_MESSAGES,
  PLACEHOLDER_START_TYPING,
} from '@const';
import type { ChatTranslations } from './Chat.types';

export const CHAT_DEFAULTS = {
  PLACEHOLDER: PLACEHOLDER_START_TYPING,
  HEIGHT: FOUR_HUNDRED,
  TYPING_TEXT: 'is typing...',
} as const;

export const CHAT_DEFAULT_TRANSLATIONS: ChatTranslations = {
  placeholder: CHAT_DEFAULTS.PLACEHOLDER,
  typingText: CHAT_DEFAULTS.TYPING_TEXT,
  newMessagesLabel: LABEL_NEW_MESSAGES,
};

export const CHAT_STICK_THRESHOLD = CHAT_STICK_THRESHOLD_PX;
export const CHAT_DEFAULT_SHOW_TIMESTAMPS = BOOLEAN_TRUE;
export const CHAT_DEFAULT_SHOW_STATUS = BOOLEAN_TRUE;
export const CHAT_DEFAULT_SHOW_AVATARS = BOOLEAN_TRUE;
export const CHAT_DEFAULT_DISABLED = BOOLEAN_FALSE;
export const CHAT_HEIGHT_VAR = '--Bear-Chat-height';
