/**
 * Sparkline constants
 */
export const SPARKLINE = {
  DEFAULT_WIDTH: 100,
  DEFAULT_HEIGHT: 32,
  DEFAULT_COLOR: '#ec4899',
  DEFAULT_STROKE_WIDTH: 2,
  VIEWBOX_SIZE: 100,
  Y_PADDING: 10,
  Y_RANGE: 80,
  CONTROL_POINT_FACTOR: 3,
  MIN_INDICATOR_COLOR: '#ef4444',
  MAX_INDICATOR_COLOR: '#10b981',
  INDICATOR_RADIUS: 3,
} as const;

