export const COMPONENT_ROUTES = [
  '/components/accordion',
  '/components/action-icon',
  '/components/active-bar',
  '/components/affix',
  '/components/alert',
  '/components/alert-dialog',
  '/components/anchor',
  '/components/animated-counter',
  '/components/app-bar',
  '/components/aspect-ratio',
  '/components/autocomplete',
  '/components/avatar',
  '/components/back-top',
  '/components/badge',
  '/components/bear-loader',
  '/components/biometric',
  '/components/blockquote',
  '/components/bottom-navigation',
  '/components/bottom-sheet',
  '/components/box',
  '/components/breadcrumbs',
  '/components/button',
  '/components/button-group',
  '/components/calendar',
  '/components/card',
  '/components/carousel',
  '/components/cascader',
  '/components/chart',
  '/components/checkbox',
  '/components/checkbox-card',
  '/components/chip',
  '/components/close-button',
  '/components/code-block',
  '/components/collapsible',
  '/components/color-picker',
  '/components/color-swatch',
  '/components/columns',
  '/components/command-palette',
  '/components/container',
  '/components/context-menu',
  '/components/copy-button',
  '/components/countdown-timer',
  '/components/credit-input',
  '/components/currency-input',
  '/components/data-table',
  '/components/date-picker',
  '/components/date-range-picker',
  '/components/descriptions',
  '/components/diff-viewer',
  '/components/divider',
  '/components/dock',
  '/components/drawer',
  '/components/dropdown',
  '/components/editable',
  '/components/empty-state',
  '/components/fab',
  '/components/fieldset',
  '/components/file-tree',
  '/components/file-upload',
  '/components/flex',
  '/components/form',
  '/components/form-control',
  '/components/form-field',
  '/components/gauge',
  '/components/glow-card',
  '/components/gradient-text',
  '/components/grid',
  '/components/heatmap',
  '/components/highlight',
  '/components/hover-card',
  '/components/image',
  '/components/input',
  '/components/input-group',
  '/components/kanban',
  '/components/kbd',
  '/components/link',
  '/components/list',
  '/components/mark',
  '/components/menu',
  '/components/modal',
  '/components/multi-select',
  '/components/number-input',
  '/components/overlay',
  '/components/pagination',
  '/components/paper',
  '/components/password-input',
  '/components/popover',
  '/components/progress',
  '/components/radio',
  '/components/scroll-area',
  '/components/segmented-control',
  '/components/select',
  '/components/sidebar',
  '/components/skeleton',
  '/components/slider',
  '/components/slider-range',
  '/components/snackbar',
  '/components/sparkline',
  '/components/spinner',
  '/components/split-button',
  '/components/spoiler',
  '/components/statistic',
  '/components/stepper',
  '/components/switch',
  '/components/tabs',
  '/components/tags-input',
  '/components/theme-icon',
  '/components/time-picker',
  '/components/timeline',
  '/components/toast',
  '/components/toggle-button',
  '/components/tooltip',
  '/components/transfer-list',
  '/components/transition',
  '/components/tree-select',
  '/components/tree-view',
  '/components/typography',
  '/components/virtual-list',
  '/components/watermark',
];

export const GETTING_STARTED_ROUTES = [
  '/',
  '/installation',
  '/theming',
  '/typescript',
  '/icons',
  '/changelog',
  '/whats-new',
  '/skills',
  '/docs/forms',
  '/docs/cli',
  '/docs/package-imports',
  '/docs/dark-mode',
  '/docs/javascript',
  '/docs/nextjs',
  '/docs/directory',
  '/roadmap',
];

export const ALL_ROUTES = [...GETTING_STARTED_ROUTES, ...COMPONENT_ROUTES];

export const DARK_MODE_SAMPLE_ROUTES = [
  '/',
  '/components/button',
  '/components/input',
  '/components/modal',
  '/components/switch',
  '/components/card',
  '/components/tabs',
  '/components/alert',
  '/components/badge',
  '/components/typography',
];

export const INTERACTION_ROUTES: Record<string, { selector: string; action: 'click' | 'fill'; value?: string; expectVisible?: string }[]> = {
  '/components/button': [
    { selector: '.doc-preview__stage .Bear-Button', action: 'click' },
  ],
  '/components/switch': [
    { selector: '.doc-preview__stage .Bear-Switch', action: 'click' },
  ],
  '/components/checkbox': [
    { selector: '.doc-preview__stage .Bear-Checkbox', action: 'click' },
  ],
  '/components/input': [
    { selector: '.doc-preview__stage .Bear-Input__input', action: 'fill', value: 'test' },
  ],
  '/components/tabs': [
    { selector: '.doc-preview__stage .Bear-Tab:nth-child(2)', action: 'click' },
  ],
  '/components/accordion': [
    { selector: '.doc-preview__stage .Bear-Accordion__trigger', action: 'click' },
  ],
  '/components/select': [
    { selector: '.doc-preview__stage .Bear-Select__trigger', action: 'click', expectVisible: '.Bear-Select__dropdown' },
  ],
  '/components/dropdown': [
    { selector: '.doc-preview__stage .Bear-Dropdown__trigger', action: 'click', expectVisible: '.Bear-Dropdown__menu' },
  ],
  '/components/collapsible': [
    { selector: '.doc-preview__stage .Bear-Collapsible__trigger', action: 'click' },
  ],
  '/components/toggle-button': [
    { selector: '.doc-preview__stage .Bear-ToggleButton', action: 'click' },
  ],
  '/components/chip': [
    { selector: '.doc-preview__stage .Bear-Chip', action: 'click' },
  ],
  '/components/segmented-control': [
    { selector: '.doc-preview__stage .Bear-SegmentedControl__item:nth-child(2)', action: 'click' },
  ],
  '/components/slider': [
    { selector: '.doc-preview__stage .Bear-Slider__thumb', action: 'click' },
  ],
  '/components/badge': [
    { selector: '.doc-preview__stage .Bear-Badge', action: 'click' },
  ],
};
