import {
  EIGHT,
  FOUR,
  SIX,
  SIX_HUNDRED_FORTY,
  TWO_HUNDRED_FORTY,
  TWO_HUNDRED_FORTY_FOUR,
  TWO_HUNDRED_TWENTY,
} from '@const';

export const COLOR_PICKER_MOBILE_QUERY = `(max-width: ${SIX_HUNDRED_FORTY}px)`;
export const COLOR_MENU_HEIGHT = TWO_HUNDRED_FORTY;
export const COLOR_MENU_HEIGHT_OFFSET = TWO_HUNDRED_FORTY_FOUR;
export const COLOR_MENU_WIDTH = TWO_HUNDRED_TWENTY;
export const COLOR_MENU_EDGE_PAD = EIGHT;
export const COLOR_MENU_GAP = FOUR;
export const COLOR_RECENT_MAX = SIX;
