import { SIXTEEN } from '@const';
import {
  AlignCenterIcon,
  AlignJustifyIcon,
  AlignLeftIcon,
  AlignRightIcon,
  BoldIcon,
  CodeIcon,
  FormatClearIcon,
  Heading1Icon,
  Heading2Icon,
  Heading3Icon,
  IndentDecreaseIcon,
  IndentIncreaseIcon,
  InsertLinkIcon,
  InsertPhotoIcon,
  ItalicIcon,
  ListBulletIcon,
  ListNumberedIcon,
  QuoteIcon,
  StrikethroughIcon,
  TableIcon,
  UnderlineIcon,
} from '../../Icon/icons/editor';

export const RICH_EDITOR_ICONS: Record<string, JSX.Element> = {
  bold: <BoldIcon size={SIXTEEN} />,
  italic: <ItalicIcon size={SIXTEEN} />,
  underline: <UnderlineIcon size={SIXTEEN} />,
  strikethrough: <StrikethroughIcon size={SIXTEEN} />,
  heading1: <Heading1Icon size={SIXTEEN} />,
  heading2: <Heading2Icon size={SIXTEEN} />,
  heading3: <Heading3Icon size={SIXTEEN} />,
  bulletList: <ListBulletIcon size={SIXTEEN} />,
  orderedList: <ListNumberedIcon size={SIXTEEN} />,
  blockquote: <QuoteIcon size={SIXTEEN} />,
  code: <CodeIcon size={SIXTEEN} />,
  link: <InsertLinkIcon size={SIXTEEN} />,
  alignLeft: <AlignLeftIcon size={SIXTEEN} />,
  alignCenter: <AlignCenterIcon size={SIXTEEN} />,
  alignRight: <AlignRightIcon size={SIXTEEN} />,
  alignJustify: <AlignJustifyIcon size={SIXTEEN} />,
  image: <InsertPhotoIcon size={SIXTEEN} />,
  indent: <IndentIncreaseIcon size={SIXTEEN} />,
  outdent: <IndentDecreaseIcon size={SIXTEEN} />,
  clearFormat: <FormatClearIcon size={SIXTEEN} />,
  table: <TableIcon size={SIXTEEN} />,
};
